Draft: details
agustinfranc/at-front pull request #43
Opened 2022-10-04 20:17 UTC by francocava

2022-10-04 23:09 UTC, agustinfranc commented on src/components/tables/ClientsTable.vue
> +    cellRenderer: (params: any) => {
dont use any

2022-10-05 15:26 UTC, agustinfranc commented on src/components/tables/LazyTable.vue
> +  <GenericTable
descarta todos estos cambios

2022-10-06 13:33 UTC, agustinfranc commented on src/views/Client/ClientDetailView.vue
> +import { useRouter, useRoute } from "vue-router";
useRouter not being used

2022-10-06 14:29 UTC, francocava commented on src/components/tables/ClientsTable.vue
> +    cellRenderer: (params: any) => {
es que con todo lo demás tira error y en la docu no aclara

2022-10-08 22:28 UTC, agustinfranc commented on src/components/forms/companion/CompanionForm.vue
> +    <TitleComponent title="Acompañante"></TitleComponent>
TitleComponent -> FormTitle

2022-10-08 22:32 UTC, agustinfranc commented on src/components/forms/extras/TitleComponent.vue
> +  title: String,
falta el required

2022-10-08 22:32 UTC, agustinfranc commented on src/api/client/index.ts
> +  getOne(params: any): AxiosPromise<Client> {
no any

2022-10-08 22:34 UTC, agustinfranc commented on src/components/tables/ClientsTable.vue
> +      @showDetails="showClient"
el evento es solo un click a la celda, no se puede llamar showDetail. vos sos el que despues quiere mosrtar un detalle con eso. por lo tanto el evento debe llamarse rowClick

2022-10-08 22:34 UTC, agustinfranc commented on src/components/tables/ClientsTable.vue
> +    path: `/clients/${id}`,
usar name y params

2022-10-08 22:35 UTC, agustinfranc commented on src/views/Client/ClientDetailView.vue
> +let loading = false;
esto no es reactivo

2022-10-08 22:36 UTC, agustinfranc commented on src/views/Client/ClientDetailView.vue
> +import TitleComponent from "../../components/forms/extras/TitleComponent.vue";
no tiene sentido que uses un componente de la carpeta form

2022-10-08 22:38 UTC, agustinfranc commented on src/components/tables/ClientsTable.vue
> +    cellRenderer: (params: any) => {
tenes el ide que te ayuda a encontrar el type

2022-10-08 22:41 UTC, agustinfranc commented on src/views/Client/ClientDetailView.vue
> +  const clientsData = await clientService.findOne(parseInt(clientId));
clientData

2022-10-10 23:07 UTC, francocava commented on src/components/tables/ClientsTable.vue
> +    cellRenderer: (params: any) => {
dice esto el ide: Parameter 'params' implicitly has an 'any' type 
y ya probe con object, array, etc

2022-10-11 01:03 UTC, agustinfranc commented on src/components/forms/companion/CompanionForm.vue
> +    <TitleComponent title="Acompañante"></TitleComponent>
no esta resuelto

2022-10-11 01:04 UTC, agustinfranc commented on src/components/tables/ClientsTable.vue
> +function showClient(id: string) {
id no es string

2022-10-11 16:19 UTC, francocava commented on src/components/forms/companion/CompanionForm.vue
> +    <TitleComponent title="Acompañante"></TitleComponent>
Me faltaba cambiarle el nombre a la variable, sorry

2022-10-11 17:01 UTC, agustinfranc commented on src/components/tables/GenericTable.vue
> +        context.emit("rowClick", event.data.id);
cellClick tiene mas sentido que se llame, por que lo cambias?

2022-10-11 17:02 UTC, agustinfranc commented on src/components/tables/GenericTable.vue
> +        context.emit("rowClick", event.data.id);
por otro lado lo estas modificando para que envie solo el id, deberia mandar toda la data

2022-10-11 17:03 UTC, agustinfranc requested changes
descartar cambios en GenericTable

2022-10-11 17:07 UTC, francocava commented on src/components/tables/GenericTable.vue
> +        context.emit("rowClick", event.data.id);
me dijiste vos que le ponga rowClick...

2022-10-11 17:15 UTC, agustinfranc commented on src/components/tables/GenericTable.vue
> +        context.emit("rowClick", event.data.id);
eso fue antes que haga lo de assignment pa, vas lento

2022-10-11 17:30 UTC, agustinfranc commented on src/components/tables/GenericTable.vue
> +      },
```suggestion
      cellWasClicked: (event: CellClickedEvent) =>
        context.emit("cellClick", event.data),
```

2022-10-11 17:30 UTC, agustinfranc commented on src/components/tables/GenericTable.vue
> +
```suggestion
```

2022-10-11 17:31 UTC, agustinfranc approved these changes

2022-10-11 17:32 UTC, merged